### ISSUE TITLE
[RFE] Build Grafana dashboards

### ISSUE THREAD

**Issue by jbiers** [rancher/ob-team-charts#107]
The Backup&Restore Operator is now able to [export metrics](https://github.com/rancher/backup-restore-operator/pull/648). Dashboards should be created to monitor these metrics in a meaningful way.

**Comment by jbiers** [comment]
Hey @omkarkhatavkar I just pushed a quick fix, you should now be able to test it properly. Just set these values in rancher-monitoring:

```yaml
rancherBackupMonitoring:
  dashboards:
    enabled: true
```

**Comment by omkarkhatavkar** [comment]
#### Verified On 

```
Rancher	v2.12-9e47832a794d17cd66b559fe2bc5c7b20f31781c-head 
Dashboard	release-2.12 a53e85f 
Rancher CLI	v2.12.0 
Helm	dev 
Machine	v0.15.0-rancher131 
rancher-monitoring-crd:69.8.2-rancher.10

```

#### Steps Executed 

- Installed the Monitoring chart with mentioned setting 

```
rancherBackupMonitoring:

  ## Deploys the rancher-backup specific dashboards. Make sure to also have metrics enabled in the rancher-backup chart.
  dashboards:
    enabled: true

```
￼

<img width="2516" height="1285" alt="Image" src="https://github.com/user-attachments/assets/3dd78cda-fdb6-46b2-9ccf-fb245418da9e" />

- Deploy BRO with metrics and the serviceMonitor enabled.
- Able to fetch the backup-restore dashboard with backup-restore metrics  

<img width="2516" height="1285" alt="Image" src="https://github.com/user-attachments/assets/fb16fc3d-55a0-42b4-9f3a-88c4a0dd2fd9" />

￼


#### Observation

The `Failed Recurring Backups over time` chart on the Rancher monitoring dashboard appears to be non-functional. It seems that when a recurring backup fails, its status changes to pending and the backup does not retry until the issue is resolved. Consequently, the backup does not recur automatically after a failure. Given this behaviour, do you think this chart remains useful or necessary?

@jbiers let me know your thoughts here for the observation ^^ 

#### Result 
Feature is working as expected apart from the observation as mentioned earlier - **Pass**

**Comment by mallardduck** [comment]
Great work @omkarkhatavkar - I think that we can look into improving that issue on the BRO side. So we should make a new issue to track that and work to solve that in a future release.

**Comment by jbiers** [comment]
> The Failed Recurring Backups over time chart on the Rancher monitoring dashboard appears to be non-functional. It seems that when a recurring backup fails, its status changes to pending and the backup does not retry until the issue is resolved. Consequently, the backup does not recur automatically after a failure. Given this behaviour, do you think this chart remains useful or necessary?

Thanks for the observation @omkarkhatavkar. There is certainly improvements to be made here. I'd say the panel is still useful in cases where a recurring backup fails a few times but then recovers by itself, which is the data we were most interested in when building the panel. This is useful because a user can open up the dashboards and check if at any point in time their recurring backups failed in the past.

**Comment by jbiers** [comment]
@omkarkhatavkar after some investigation I found there are two problems here causing data to not appear in the panel you mentioned.

First one is the panel has an override, it was probably left there by mistake when I finished editing the dashboard. I opened a PR to fix that. If you test from my new branch, you should at least see the dots in the panel now (even if zeroed out for most cases), as opposed to an empty panel as is the case now.

```
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: bro-dashboards-recurring-failed
spec:
  gitBranch: bro-dashboards-recurring-failed
  gitRepo: https://github.com/jbiers/ob-team-charts
```

The other problem is related to how BRO updates the backupType field in backups.
This panel filters backups to only include those that have backupType="Recurring". However, BRO's control flow tries to execute the backup **before** actually updating the field. So, backups that never succeeded will not show up as part of the data. I'll have a separate PR to fix that for 2.12.2 (September).

If we apply the first fix, the panel will be functional for any recurring backups that succeeded at least once, and users can track the data for any future problems with them.
