### ISSUE TITLE
[v2.11][Logging] Add support for priorityClassName on DaemonSets

### ISSUE THREAD

**Issue by mallardduck** [rancher/ob-team-charts#32]
Per title this is to track the changes made to add priorityClassName to DaemonSets on the chart.
This work was done here: https://github.com/rancher/ob-team-charts/pull/31

The chart still needs to be synced from `ob-team-charts` into `rancher/charts` - targeting 2.11.1

**Comment by mallardduck** [comment]
@jmeza-xyz has prepared a PR for rancher/charts to incorporate this change here: https://github.com/rancher/charts/pull/5212

**Comment by prachidamle** [comment]
@mallardduck The branches have been unfrozen now, can you merge this in now pls?

**Comment by mallardduck** [comment]
Working with @jmeza-xyz now to refresh their PR so we can merge today.

**Comment by mallardduck** [comment]
Ready to test as: rancher-logging 106.0.1-rc.1+up4.10.0-rancher.2

**Comment by deepakpunia-suse** [comment]
Below is the bug verification details. 

Details
rancher: `v2.11-head`
RKE2 : `v1.31.7+rke2r1`
Rancher-logging : `106.0.1-rc.1+up4.10.0-rancher.2`

![Image](https://github.com/user-attachments/assets/6a1f897a-fea6-4993-a3d2-3641103ba76c)

1. Install logging with blank podPriorityClassName and priorityClassName

`values.yaml addition`
```
fluentbit:
  podPriorityClassName: ""
fluentd:
  podPriorityClassName: ""
priorityClassName: ""
```

2. Install logging with with system existing podPriorityClassName and priorityClassName

```
# kubectl get priorityclass
NAME                      VALUE        GLOBAL-DEFAULT   AGE
rancher-critical          1000000000   false            21m
system-cluster-critical   2000000000   false            31m
system-node-critical      2000001000   false            31m
```

`values.yaml addition`
```
fluentbit:
  podPriorityClassName: system-cluster-critical
fluentd:
  podPriorityClassName: system-cluster-critical
priorityClassName: rancher-critical
```

![Image](https://github.com/user-attachments/assets/bde2eb44-4226-4bfb-a64f-dc3e2a1a3af1)

3. Create new PriorityClass and test logging installation with it

```
# k get PriorityClass | grep test
global-level-test         111111111    false            21s
resource-level-test       111111111    false            96s
```

`values.yaml addition`
```
fluentbit:
  podPriorityClassName: resource-level-test
fluentd:
  replicas: 1
  podPriorityClassName: resource-level-test
priorityClassName: global-level-test
```
![Image](https://github.com/user-attachments/assets/b3d5d0bc-533d-4ec6-b7df-82ec7a06c486)


4. Check syslog created by Logging : Passed

![Image](https://github.com/user-attachments/assets/e2f017c1-7c9b-42a1-9d1b-299ff6599ce7)

![Image](https://github.com/user-attachments/assets/89dcbb25-11a8-4363-9099-5c8053fe4dc6)
