### ISSUE TITLE
[QA][ob-team-charts] rancher-monitoring 69.8.2-rancher.1

### ISSUE THREAD

**Issue by mallardduck** [rancher/ob-team-charts#66]
### Pull Request

https://github.com/rancher/ob-team-charts/pull/51

### Root Issue

https://github.com/rancher/rancher/issues/48108

### ClusterRepo Config for QA

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: ob-team-charts-jbiers
spec:
  gitBranch: rancher-monitoring-69.8.2
  gitRepo: https://github.com/jbiers/ob-team-charts
```

### Testing Considerations

This is a new Rebase from upstream with new image versions and the most significant being Prom 3.0 updates.
