### ISSUE TITLE
[QA][ob-team-charts] rancher-monitoring 66.7.1-rancher.11

### ISSUE THREAD

**Issue by jbiers** [rancher/ob-team-charts#67]
### Pull Request

https://github.com/rancher/ob-team-charts/pull/61

### Root Issue

https://github.com/rancher/rancher/issues/49911

### ClusterRepo Config for QA

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: ob-team-charts-skanakal
spec:
  gitBranch: grafana-rewrites
  gitRepo: https://github.com/skanakal/ob-team-charts
```

### Testing Considerations

- Need to setup an Azure Monitor and import it into Grafana
- Need to be able to access the Azure datasource via Rancher -> Grafana or straight from the reverse proxy address.

Important values:
```yaml
grafana.ini:    
  server: 
    domain: grafana.<public-ip>.sslip.io
    root_url: "%(protocol)s://%(domain)s/"
    serve_from_sub_path: true
ingress:    
  annotations: {}
  enabled: true
  hosts:
  - grafana.<public-ip>.sslip.io
  labels: {}
  path: /
  tls: []    
  ingressClassName: nginx  
```
