### ISSUE TITLE
[QA][ob-team-charts] rancher-project-monitoring 0.6.0

### ISSUE THREAD

**Issue by jbiers** [rancher/ob-team-charts#70]
### Pull Request

https://github.com/rancher/ob-team-charts/pull/69

### Root Issue

https://github.com/rancher/rancher/issues/48108

### ClusterRepo Config for QA

N/A

### Testing Considerations

The rancher-project-monitoring chart is embedded in the prometheus-federator image and can be tested before merging with the following steps:

- I created a prometheus-federator image which the latest rancher-project-monitoring chart in my personal Dockerhub repository. You can find it [here](https://hub.docker.com/layers/jbiers/prometheus-federator/rpm-0.6.0/images/sha256-9d58cec87a5a534ce7514a63c54248004b87d811f6da01150e86c7156d5fe759).
- Deploy the latest prometheus-federator chart version from the Apps tab, but select `Customize Helm options before install` and change the prometheus-federator image version to be:

```yaml
helmProjectOperator:
  image:
    pullPolicy: IfNotPresent
    registry: ''
    repository: jbiers/prometheus-federator
    tag: rpm-0.6.0
```

Run the prometheus-federator validation tests as usual.

**Comment by deepakpunia-suse** [comment]
**Bug Verification Details:**

* **Rancher:** `v2.11-head`
* **RKE2:** `v1.31.8+rke2r1`
* **prometheus-federator:** `latest available chart` (from `ob-team-charts`)

**Steps Performed:**

1.  Configured the Rancher instance to use the `ob-team-charts` ClusterRepo.
2.  Installed the Rancher Monitoring chart.
3.  Deployed the latest `prometheus-federator` chart version from `ob-team-charts`, ensuring the `helmProjectOperator` used the following image:
    ```yaml
    helmProjectOperator:
      image:
        pullPolicy: IfNotPresent
        registry: ''
        repository: jbiers/prometheus-federator
        tag: rpm-0.6.0
    ```
4.  Verified that the relevant pod was created using the image `jbiers/prometheus-federator:rpm-0.6.0`.

![Image](https://github.com/user-attachments/assets/6219d3db-bbf6-4bdf-82ae-91579f79b9fc)

5.  Executed `prometheus-federator` validation tests, including Project Monitor functionality.

![Image](https://github.com/user-attachments/assets/da8b8f2c-3a73-4ecc-9697-d6d708db99ef)
