### ISSUE TITLE
[QA][ob-team-charts] monitoring 66.7.1-rancher.11

### ISSUE THREAD

**Issue by mallardduck** [rancher/ob-team-charts#77]
### Pull Request

https://github.com/rancher/ob-team-charts/pull/76

### Root Issue

https://github.com/rancher/rancher/issues/50263

### ClusterRepo Config for QA

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: ob-team-charts-dpock-tags-bug
spec:
  gitBranch: 66.7-fix-image-tags
  gitRepo: https://github.com/mallardduck/ob-team-charts
```

### Testing Considerations

The affected subcharts were:
- Grafana
- Prom NodeExporter
- Windows Exporter

Because Grafana was changed this also included an update to Rancher Project Monitoring. This doesn't need to be tested as part of this issue as PromFed+Project Monitoring parts should be covered as part of `rancher/charts` merging related to the parent issue.

**Comment by deepakpunia-suse** [comment]
**Bug Verification Details:**

  * **Rancher:** `v2.11-head`
  * **RKE2:** `v1.31.9-rc2+rke2r1`
  * **AKS:** `1.31.7` (Downstream cluster with Windows Worker Node)



1.  Install upstream and downstream clusters with Windows worker nodes.

2.  Configure the following `ClusterRepo`:

    ```yaml
    apiVersion: catalog.cattle.io/v1
    kind: ClusterRepo
    metadata:
      name: ob-team-charts-dpock-tags-bug
    spec:
      gitBranch: 66.7-fix-image-tags
      gitRepo: https://github.com/mallardduck/ob-team-charts
    ```

3.  Check various alerts, graphs, and charts including:

      * Grafana
      * Prometheus Node Exporter
      * Windows Exporter

4.  Windows Exporter status: (Screenshot)

![Image](https://github.com/user-attachments/assets/7e146f7c-fd66-4220-8942-c1878dcdeb57)

5.  New images pod status: (Screenshot)

![Image](https://github.com/user-attachments/assets/5d304279-56df-4e1d-a0b9-63beb701e3db)

![Image](https://github.com/user-attachments/assets/2f807fe5-24ab-4bb1-ac8b-9ff10a918332)

![Image](https://github.com/user-attachments/assets/3f077de5-0ebf-4c7f-a040-9455a0db5807)


5. Chart installation 
![Image](https://github.com/user-attachments/assets/ece5a042-7f8d-4a34-beea-b415fb8c602f)
