### ISSUE TITLE
[monitoring all] Cannot easily update the PushProx image used across all subcharts

### ISSUE THREAD

**Issue by mallardduck** [rancher/ob-team-charts#79]
### Chart Slug

rancher-monitoring

### Affected Chart Versions

all

### Bug Details

Per title, if a user wants to update PushProx image they logically will want it updated for all instances in a deployment. Today that sort of image tag update would take a lot of effort where they have to add `image.tag` under every subcharts field in `values.yaml`.

### Expected Behavior

As an alternative to that, we should allow users to do:

```yaml
global:
  ## Global overrides for PushProx image values
  pushProx:
    image:
      repository: rancher/pushprox
      tag: "YOUR VERSION"
  ## Alternatively, specify different client/proxy images via:
    proxyImage:
      repository: rancher/pushprox-proxy
      tag: "YOUR VERSION"
    clientsImage:
      repository: rancher/pushprox-client
      tag: "YOUR VERSION"
```

Where the precedence is set as:
1. If set use `.global.pushProx.{proxyImage/clientsImage}` values,
2. Else if set use `.global.pushProx.image` values,
3. Else use local (to PushProx chart) `.Values.{clients/proxy}.image` values.

In our Monitoring charts we should set this up as commented out values like:

```yaml
  ## Global overrides for PushProx image values
  # pushProx:
  #   image:
  #     repository: rancher/pushprox
  #     tag: "YOUR VERSION"
  ## Alternatively, specify different client/proxy images via:
  #   proxyImage:
  #     repository: rancher/pushprox-proxy
  #     tag: "YOUR VERSION"
  #   clientsImage:
  #     repository: rancher/pushprox-client
  #     tag: "YOUR VERSION"
```
