### ISSUE TITLE
[QA][ob-team-charts] logging 4.10.0-rancher.9

### ISSUE THREAD

**Issue by skanakal** [rancher/ob-team-charts#97]
### Pull Request

https://github.com/rancher/ob-team-charts/pull/96

### Root Issue

https://github.com/rancher/rancher/issues/50627

### ClusterRepo Config for QA

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: ob-team-charts-skanakal
spec:
  gitBranch: fluentbit-klog
  gitRepo: https://github.com/skanakal/ob-team-charts.git
```

### Testing Considerations

- Add extra output to see the logs as below:
```
-     [OUTPUT]
        Name              stdout
        Match             *
        Format            json_lines
        json_date_format  iso8601
```

**Comment by pankajsqe** [comment]
Test Pass : Time format is coming with microseconds `1750260028.309585000` and `15:20:28.309585`

Detail
Rancher : V2.11.3-alpha2
Loggin: rancher-logging:4.10.0-rancher.9

Cluster Repo
```
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: ob-team-charts-skanakal
spec:
  gitBranch: fluentbit-klog
  gitRepo: https://github.com/skanakal/ob-team-charts.git
```

Setup
```
-     [OUTPUT]
        Name              stdout
        Match             *

```

**Logs**
[0] rke2_kubelet: [[1750260028.309585000, {}], {"level"=>"I", "timestamp"=>"0618 15:20:28.309585", "thread_id"=>"2028", "filename"=>"kubelet_volumes.go", "linenumber"=>"163", "message"=>""Cleaned up orphaned pod volumes dir" podUID="f3d10cfe-172f-46bd-a502-fec4ffce3679" path="/var/lib/kubelet/pods/f3d10cfe-172f-46bd-a502-fec4ffce3679/volumes""}]

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/500752f5-7190-4f35-9ffc-34f1f8931dcb" />

-------------------------------------------------------------------------------------------------------------------------

Setup

```
-     [OUTPUT]
        Name              stdout
        Match             *
        Format            json_lines
        json_date_format  iso8601
```

Expected Time with microsecond
date":"2025-06-18T16:23:09.**491139**Z"


**Logs**
{"**date":"2025-06-18T16:23:09.491139Z","level":"I","timestamp":"0618 16:23:09.491139","thread_id":"1977**","filename":"event.go","linenumber":"389","message":"\"Event occurred\" object=\"local-on-demand-ip-172-31-17-250-1750263789-af69f0\" fieldPath=\"\" kind=\"ETCDSnapshotFile\" apiVersion=\"k3s.cattle.io/v1\" type=\"Normal\" reason=\"ETCDSnapshotCreated\" message=\"Snapshot on-demand-ip-172-31-17-250-1750263789 saved on ip-172-31-17-250\""}


<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/4ddfd602-ccf8-48be-9ad7-8e5e87111b61" />
